<?php
return [
    'estados_civis' => [
        'Solteiro',
        'Casado',
        'Separado',
        'Divorciado',
        'Viúvo',
    ],
    'profissoes' => [
        'Administrador',
        'Advogado',
        'Agente de Segurança',
        'Arquiteto',
        'Artista',
        'Assistente Administrativo',
        'Assistente Social',
        'Atendente',
        'Autônomo',
        'Bancário',
        'Bibliotecário',
        'Biólogo',
        'Cabeleireiro',
        'Cantor',
        'Contador',
        'Cozinheiro',
        'Designer Gráfico',
        'Desenvolvedor',
        'Dentista',
        'Economista',
        'Eletricista',
        'Enfermeiro',
        'Engenheiro Civil',
        'Engenheiro Mecânico',
        'Empresário',
        'Farmacêutico',
        'Fisioterapeuta',
        'Fotógrafo',
        'Funcionário Público',
        'Garçom',
        'Jornalista',
        'Marceneiro',
        'Médico',
        'Motorista',
        'Nutricionista',
        'Pedreiro',
        'Professor',
        'Recepcionista',
        'Secretário',
        'Segurança',
        'Soldador',
        'Técnico em Informática',
        'Vendedor',
        'Veterinário',
        'Outro',
    ],
];
