<?php
return [
    'nacionalidades' => [
        [ 'value' => "br", 'flag' => "br", 'text' => "Brasileiro(a)" ],
        [ 'value' => "af", 'flag' => "af", 'text' => "Afegão(a)" ],
        [ 'value' => "al", 'flag' => "al", 'text' => "Albanês(a)" ],
        [ 'value' => "dz", 'flag' => "dz", 'text' => "Argelino(a)" ],
        [ 'value' => "ao", 'flag' => "ao", 'text' => "Angolano(a)" ],
        [ 'value' => "ar", 'flag' => "ar", 'text' => "Argentino(a)" ],
        [ 'value' => "am", 'flag' => "am", 'text' => "Armênio(a)" ],
        [ 'value' => "au", 'flag' => "au", 'text' => "Australiano(a)" ],
        [ 'value' => "at", 'flag' => "at", 'text' => "Austriaco(a)" ],
        [ 'value' => "az", 'flag' => "az", 'text' => "Azerbaijano(a)" ],
        [ 'value' => "bs", 'flag' => "bs", 'text' => "Bahamense" ],
        [ 'value' => "bh", 'flag' => "bh", 'text' => "Bareinita(o)" ],
        [ 'value' => "bd", 'flag' => "bd", 'text' => "Bangladeshiano(a)" ],
        [ 'value' => "be", 'flag' => "be", 'text' => "Belga" ],
        [ 'value' => "bz", 'flag' => "bz", 'text' => "Belizenho(a)" ],
        [ 'value' => "bj", 'flag' => "bj", 'text' => "Beninense" ],
        [ 'value' => "bt", 'flag' => "bt", 'text' => "Butanês(a)" ],
        [ 'value' => "by", 'flag' => "by", 'text' => "Bielorrusso(a)" ],
        [ 'value' => "bo", 'flag' => "bo", 'text' => "Boliviano(a)" ],
        [ 'value' => "ba", 'flag' => "ba", 'text' => "Bósnio(a)" ],
        [ 'value' => "bw", 'flag' => "bw", 'text' => "Botsuano(a)" ],
        [ 'value' => "bn", 'flag' => "bn", 'text' => "Bruneano(a)" ],
        [ 'value' => "bg", 'flag' => "bg", 'text' => "Búlgaro(a)" ],
        [ 'value' => "bf", 'flag' => "bf", 'text' => "Burquinense" ],
        [ 'value' => "bi", 'flag' => "bi", 'text' => "Burundês(a)" ],
        [ 'value' => "cv", 'flag' => "cv", 'text' => "Cabo-verdiano(a)" ],
        [ 'value' => "kh", 'flag' => "kh", 'text' => "Cambojano(a)" ],
        [ 'value' => "cm", 'flag' => "cm", 'text' => "Camarones(a)" ],
        [ 'value' => "ca", 'flag' => "ca", 'text' => "Canadense" ],
        [ 'value' => "qa", 'flag' => "qa", 'text' => "Catarense" ],
        [ 'value' => "td", 'flag' => "td", 'text' => "Chadiano(a)" ],
        [ 'value' => "cl", 'flag' => "cl", 'text' => "Chileno(a)" ],
        [ 'value' => "cn", 'flag' => "cn", 'text' => "Chinês(a)" ],
        [ 'value' => "cy", 'flag' => "cy", 'text' => "Chipriota" ],
        [ 'value' => "co", 'flag' => "co", 'text' => "Colombiano(a)" ],
        [ 'value' => "km", 'flag' => "km", 'text' => "Comorense" ],
        [ 'value' => "cd", 'flag' => "cd", 'text' => "Congolês(a) (RDC)" ],
        [ 'value' => "cg", 'flag' => "cg", 'text' => "Congolês(a)" ],
        [ 'value' => "cr", 'flag' => "cr", 'text' => "Costarriquenho(a)" ],
        [ 'value' => "hr", 'flag' => "hr", 'text' => "Croata" ],
        [ 'value' => "cu", 'flag' => "cu", 'text' => "Cubano(a)" ],
        [ 'value' => "dk", 'flag' => "dk", 'text' => "Dinamarquês(a)" ],
        [ 'value' => "dj", 'flag' => "dj", 'text' => "Djibutiano(a)" ],
        [ 'value' => "do", 'flag' => "do", 'text' => "Dominicano(a)" ],
        [ 'value' => "ec", 'flag' => "ec", 'text' => "Equatoriano(a)" ],
        [ 'value' => "eg", 'flag' => "eg", 'text' => "Egípcio(a)" ],
        [ 'value' => "sv", 'flag' => "sv", 'text' => "Salvadorenho(a)" ],
        [ 'value' => "gq", 'flag' => "gq", 'text' => "Equatoguineano(a)" ],
        [ 'value' => "er", 'flag' => "er", 'text' => "Eritreano(a)" ],
        [ 'value' => "ee", 'flag' => "ee", 'text' => "Estoniano(a)" ],
        [ 'value' => "et", 'flag' => "et", 'text' => "Etíope" ],
        [ 'value' => "fj", 'flag' => "fj", 'text' => "Fijiano(a)" ],
        [ 'value' => "fi", 'flag' => "fi", 'text' => "Finlandês(a)" ],
        [ 'value' => "fr", 'flag' => "fr", 'text' => "Francês(a)" ],
        [ 'value' => "ga", 'flag' => "ga", 'text' => "Gabonês(a)" ],
        [ 'value' => "gm", 'flag' => "gm", 'text' => "Gambiano(a)" ],
        [ 'value' => "ge", 'flag' => "ge", 'text' => "Georgiano(a)" ],
        [ 'value' => "de", 'flag' => "de", 'text' => "Alemão(a)" ],
        [ 'value' => "gh", 'flag' => "gh", 'text' => "Ganaense" ],
        [ 'value' => "gr", 'flag' => "gr", 'text' => "Grego(a)" ],
        [ 'value' => "gd", 'flag' => "gd", 'text' => "Granadino(a)" ],
        [ 'value' => "gt", 'flag' => "gt", 'text' => "Guatemalteco(a)" ],
        [ 'value' => "gn", 'flag' => "gn", 'text' => "Guineense" ],
        [ 'value' => "gw", 'flag' => "gw", 'text' => "Guineense-Bissau" ],
        [ 'value' => "gy", 'flag' => "gy", 'text' => "Guyanês(a)" ],
        [ 'value' => "ht", 'flag' => "ht", 'text' => "Haitiano(a)" ],
        [ 'value' => "hn", 'flag' => "hn", 'text' => "Hondurenho(a)" ],
        [ 'value' => "hu", 'flag' => "hu", 'text' => "Húngaro(a)" ],
        [ 'value' => "is", 'flag' => "is", 'text' => "Islandês(a)" ],
        [ 'value' => "in", 'flag' => "in", 'text' => "Indiano(a)" ],
        [ 'value' => "id", 'flag' => "id", 'text' => "Indonésio(a)" ],
        [ 'value' => "ir", 'flag' => "ir", 'text' => "Iraniano(a)" ],
        [ 'value' => "iq", 'flag' => "iq", 'text' => "Iraquiano(a)" ],
        [ 'value' => "ie", 'flag' => "ie", 'text' => "Irlandês(a)" ],
        [ 'value' => "il", 'flag' => "il", 'text' => "Israelense" ],
        [ 'value' => "it", 'flag' => "it", 'text' => "Italiano(a)" ],
        [ 'value' => "jm", 'flag' => "jm", 'text' => "Jamaicano(a)" ],
        [ 'value' => "jp", 'flag' => "jp", 'text' => "Japonês(a)" ],
        [ 'value' => "jo", 'flag' => "jo", 'text' => "Jordano(a)" ],
        [ 'value' => "kz", 'flag' => "kz", 'text' => "Cazaque(a)" ],
        [ 'value' => "ke", 'flag' => "ke", 'text' => "Queniano(a)" ],
        [ 'value' => "ki", 'flag' => "ki", 'text' => "Kiribatiano(a)" ],
        [ 'value' => "kw", 'flag' => "kw", 'text' => "Kuwaitiano(a)" ],
        [ 'value' => "kg", 'flag' => "kg", 'text' => "Quirguiz(a)" ],
        [ 'value' => "la", 'flag' => "la", 'text' => "Laosiano(a)" ],
        [ 'value' => "lv", 'flag' => "lv", 'text' => "Letão(a)" ],
        [ 'value' => "lb", 'flag' => "lb", 'text' => "Libanês(a)" ],
        [ 'value' => "ls", 'flag' => "ls", 'text' => "Lesotiano(a)" ],
        [ 'value' => "lr", 'flag' => "lr", 'text' => "Liberiano(a)" ],
        [ 'value' => "ly", 'flag' => "ly", 'text' => "Líbio(a)" ],
        [ 'value' => "li", 'flag' => "li", 'text' => "Liechtensteinense" ],
        [ 'value' => "lt", 'flag' => "lt", 'text' => "Lituano(a)" ],
        [ 'value' => "lu", 'flag' => "lu", 'text' => "Luxemburguês(a)" ],
        [ 'value' => "mk", 'flag' => "mk", 'text' => "Macedônio(a)" ],
        [ 'value' => "mg", 'flag' => "mg", 'text' => "Malgaxe" ],
        [ 'value' => "mw", 'flag' => "mw", 'text' => "Malawiano(a)" ],
        [ 'value' => "my", 'flag' => "my", 'text' => "Malaio(a)" ],
        [ 'value' => "mv", 'flag' => "mv", 'text' => "Maldivo(a)" ],
        [ 'value' => "ml", 'flag' => "ml", 'text' => "Maliano(a)" ],
        [ 'value' => "mt", 'flag' => "mt", 'text' => "Maltês(a)" ],
        [ 'value' => "ma", 'flag' => "ma", 'text' => "Marroquino(a)" ],
        [ 'value' => "mu", 'flag' => "mu", 'text' => "Mauriciano(a)" ],
        [ 'value' => "mx", 'flag' => "mx", 'text' => "Mexicano(a)" ],
        [ 'value' => "fm", 'flag' => "fm", 'text' => "Micronésio(a)" ],
        [ 'value' => "md", 'flag' => "md", 'text' => "Moldávio(a)" ],
        [ 'value' => "mc", 'flag' => "mc", 'text' => "Monegasco(a)" ],
        [ 'value' => "mn", 'flag' => "mn", 'text' => "Mongol(a)" ],
        [ 'value' => "me", 'flag' => "me", 'text' => "Montenegrino(a)" ],
        [ 'value' => "mz", 'flag' => "mz", 'text' => "Moçambicano(a)" ],
        [ 'value' => "na", 'flag' => "na", 'text' => "Namibiano(a)" ],
        [ 'value' => "nr", 'flag' => "nr", 'text' => "Nauruano(a)" ],
        [ 'value' => "np", 'flag' => "np", 'text' => "Nepalês(a)" ],
        [ 'value' => "nl", 'flag' => "nl", 'text' => "Neerlandês(a)" ],
        [ 'value' => "nz", 'flag' => "nz", 'text' => "Neo-zelandês(a)" ],
        [ 'value' => "ni", 'flag' => "ni", 'text' => "Nicaraguense" ],
        [ 'value' => "ne", 'flag' => "ne", 'text' => "Nigerino(a)" ],
        [ 'value' => "ng", 'flag' => "ng", 'text' => "Nigeriano(a)" ],
        [ 'value' => "kp", 'flag' => "kp", 'text' => "Coreano(a) do Norte" ],
        [ 'value' => "kr", 'flag' => "kr", 'text' => "Coreano(a) do Sul" ],
        [ 'value' => "no", 'flag' => "no", 'text' => "Norueguês(a)" ],
        [ 'value' => "om", 'flag' => "om", 'text' => "Omãense" ],
        [ 'value' => "pk", 'flag' => "pk", 'text' => "Paquistanês(a)" ],
        [ 'value' => "pw", 'flag' => "pw", 'text' => "Palauano(a)" ],
        [ 'value' => "pa", 'flag' => "pa", 'text' => "Panamenho(a)" ],
        [ 'value' => "pg", 'flag' => "pg", 'text' => "Papua-novoguineense" ],
        [ 'value' => "py", 'flag' => "py", 'text' => "Paraguaio(a)" ],
        [ 'value' => "pe", 'flag' => "pe", 'text' => "Peruano(a)" ],
        [ 'value' => "ph", 'flag' => "ph", 'text' => "Filipino(a)" ],
        [ 'value' => "pl", 'flag' => "pl", 'text' => "Polonês(a)" ],
        [ 'value' => "pt", 'flag' => "pt", 'text' => "Português(a)" ],
        [ 'value' => "ro", 'flag' => "ro", 'text' => "Romeno(a)" ],
        [ 'value' => "ru", 'flag' => "ru", 'text' => "Russo(a)" ],
        [ 'value' => "rw", 'flag' => "rw", 'text' => "Ruandês(a)" ],
        [ 'value' => "kn", 'flag' => "kn", 'text' => "São-cristovense" ],
        [ 'value' => "lc", 'flag' => "lc", 'text' => "São-lucense" ],
        [ 'value' => "vc", 'flag' => "vc", 'text' => "São-vicentense" ],
        [ 'value' => "ws", 'flag' => "ws", 'text' => "Samoano(a)" ],
        [ 'value' => "sm", 'flag' => "sm", 'text' => "San-marinhense" ],
        [ 'value' => "st", 'flag' => "st", 'text' => "Santomense" ],
        [ 'value' => "sa", 'flag' => "sa", 'text' => "Saudita" ],
        [ 'value' => "sn", 'flag' => "sn", 'text' => "Senegalês(a)" ],
        [ 'value' => "rs", 'flag' => "rs", 'text' => "Sérvio(a)" ],
        [ 'value' => "sc", 'flag' => "sc", 'text' => "Seychellense" ],
        [ 'value' => "sl", 'flag' => "sl", 'text' => "Sierra-leonês(a)" ],
        [ 'value' => "sg", 'flag' => "sg", 'text' => "Singaporeano(a)" ],
        [ 'value' => "sk", 'flag' => "sk", 'text' => "Eslovaco(a)" ],
        [ 'value' => "si", 'flag' => "si", 'text' => "Esloveno(a)" ],
        [ 'value' => "sb", 'flag' => "sb", 'text' => "Salomonense" ],
        [ 'value' => "so", 'flag' => "so", 'text' => "Somali(a)" ],
        [ 'value' => "za", 'flag' => "za", 'text' => "Sul-africano(a)" ],
        [ 'value' => "es", 'flag' => "es", 'text' => "Espanhol(a)" ],
        [ 'value' => "lk", 'flag' => "lk", 'text' => "Cingalês(a)" ],
        [ 'value' => "sd", 'flag' => "sd", 'text' => "Sudanês(a)" ],
        [ 'value' => "sr", 'flag' => "sr", 'text' => "Surinamês(a)" ],
        [ 'value' => "sz", 'flag' => "sz", 'text' => "Suazi(a)" ],
        [ 'value' => "se", 'flag' => "se", 'text' => "Sueco(a)" ],
        [ 'value' => "ch", 'flag' => "ch", 'text' => "Suíço(a)" ],
        [ 'value' => "sy", 'flag' => "sy", 'text' => "Sírio(a)" ],
        [ 'value' => "tj", 'flag' => "tj", 'text' => "Tadjique(a)" ],
        [ 'value' => "tz", 'flag' => "tz", 'text' => "Tanzaniano(a)" ],
        [ 'value' => "th", 'flag' => "th", 'text' => "Tailandês(a)" ],
        [ 'value' => "tl", 'flag' => "tl", 'text' => "Timorense" ],
        [ 'value' => "tg", 'flag' => "tg", 'text' => "Togolês(a)" ],
        [ 'value' => "to", 'flag' => "to", 'text' => "Tonganês(a)" ],
        [ 'value' => "tt", 'flag' => "tt", 'text' => "Trinitário(a)" ],
        [ 'value' => "tn", 'flag' => "tn", 'text' => "Tunisiano(a)" ],
        [ 'value' => "tr", 'flag' => "tr", 'text' => "Turco(a)" ],
        [ 'value' => "tm", 'flag' => "tm", 'text' => "Turcomeno(a)" ],
        [ 'value' => "tv", 'flag' => "tv", 'text' => "Tuvaluano(a)" ],
        [ 'value' => "ug", 'flag' => "ug", 'text' => "Ugandense" ],
        [ 'value' => "ua", 'flag' => "ua", 'text' => "Ucraniano(a)" ],
        [ 'value' => "ae", 'flag' => "ae", 'text' => "Emiradense" ],
        [ 'value' => "gb", 'flag' => "gb", 'text' => "Inglês(a)" ],
        [ 'value' => "us", 'flag' => "us", 'text' => "Americano(a)" ],
        [ 'value' => "uy", 'flag' => "uy", 'text' => "Uruguaio(a)" ],
        [ 'value' => "uz", 'flag' => "uz", 'text' => "Uzbeque(a)" ],
        [ 'value' => "vu", 'flag' => "vu", 'text' => "Vanuatuense" ],
        [ 'value' => "va", 'flag' => "va", 'text' => "Vaticano(a)" ],
        [ 'value' => "ve", 'flag' => "ve", 'text' => "Venezuelano(a)" ],
        [ 'value' => "vn", 'flag' => "vn", 'text' => "Vietnamita" ],
        [ 'value' => "ye", 'flag' => "ye", 'text' => "Iemenita" ],
        [ 'value' => "zm", 'flag' => "zm", 'text' => "Zambiano(a)" ],
        [ 'value' => "zw", 'flag' => "zw", 'text' => "Zimbabuano(a)" ]
    ],
    'estados_civis' => [
        'Solteiro(a)',
        'Casado(a)',
        'Separado(a)',
        'Divorciado(a)',
        'Viúvo(a)',
    ],
    'profissoes' => [
        'Administrador(a)',
        'Advogado(a)',
        'Agente de Segurança',
        'Arquiteto(a)',
        'Artista',
        'Assistente Administrativo(a)',
        'Assistente Social',
        'Atendente',
        'Autônomo(a)',
        'Bancário(a)',
        'Bibliotecário(a)',
        'Biólogo(a)',
        'Cabeleireiro(a)',
        'Cantor(a)',
        'Contador(a)',
        'Cozinheiro(a)',
        'Designer Gráfico(a)',
        'Desenvolvedor(a) de Software',
        'Dentista',
        'Economista',
        'Eletricista',
        'Enfermeiro(a)',
        'Engenheiro(a) Civil',
        'Engenheiro(a) Mecânico',
        'Empresário(a)',
        'Farmacêutico(a)',
        'Fisioterapeuta',
        'Fotógrafo(a)',
        'Funcionário(a) Público(a)',
        'Garçom',
        'Jornalista',
        'Marceneiro',
        'Médico(a)',
        'Motorista',
        'Nutricionista',
        'Pedreiro(a)',
        'Professor(a)',
        'Recepcionista',
        'Secretário(a)',
        'Segurança',
        'Soldador(a)',
        'Técnico(a) em Informática',
        'Vendedor(a)',
        'Veterinário(a)',
    ],
];
